name: Post Daily Tweet

on:
  schedule:
    - cron: "20 8 * * *"  # Runs at 8:00 AM UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Fetch the full history of the repository, including the day_counter.txt
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests requests_oauthlib

    - name: Run the bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: |
        python main.py

    - name: Commit updated day count
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add day_counter.txt
        git commit -m "Increment day count"
        git push
